### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by ghost** [vertexclique/lever#21]
Hi, thank you for creating this lib.

Today I'm working with Bastion, a lib that uses your Lever library. When I build with rust version 1.56.1, it leads to error like this:

```rust
error[E0532]: expected tuple struct or tuple variant, found function `Ok`
   --> src/table/lotable.rs:270:13
    |
270 |             Ok(init_frame) => init_frame.get().0.clone(),
    |             ^^ not a tuple struct or tuple variant
    |
help: consider importing one of these items instead
    |
1   | use core::result::Result::Ok;
    |
1   | use std::result::Result::Ok;
    |

error[E0532]: expected tuple struct or tuple variant, found function `Ok`
   --> src/table/lotable.rs:338:20
    |
338 |             if let Ok(read) = self.txn.begin(|t| {
    |                    ^^ not a tuple struct or tuple variant
    |
help: consider importing one of these items instead
    |
1   | use core::result::Result::Ok;
    |
1   | use std::result::Result::Ok;
    |

error[E0532]: expected tuple struct or tuple variant, found function `Ok`
   --> src/table/lotable.rs:364:16
    |
364 |         if let Ok(frame_len) = self.txn.begin(|t| t.read(&tvar)) {
    |                ^^ not a tuple struct or tuple variant
    |
help: consider importing one of these items instead
    |
1   | use core::result::Result::Ok;
    |
1   | use std::result::Result::Ok;
```

I'm using CentOS 8 WSL, my other machine have the same issue with Rust v1.56.
How can I fix it? Or could you guys update with newest version?

Thank you.

**Comment by hardliner66** [comment]
You can work around that issue by cloning the pull request #22 into a local dir and create a patch entry in your cargo.toml (e.g.: https://github.com/TwChallenge/mapmaster/blob/integrate-bastion/Cargo.toml#L25-L26).

This should fix the problem until a new version can be published.

**Comment by vertexclique** [comment]
Solved! 0.1.2 released.

**Comment by ghost** [comment]
> You can work around that issue by cloning the pull request #22 into a local dir and create a patch entry in your cargo.toml (e.g.: https://github.com/TwChallenge/mapmaster/blob/integrate-bastion/Cargo.toml#L25-L26).
> 
> This should fix the problem until a new version can be published.

Thanh you!
